"use client";

import { useEffect, useState } from "react";
import { ChevronDown, CalendarDays, HeartPulse } from "lucide-react";
import { Capacitor } from "@capacitor/core";
import { Button } from "@/components/ui/button";
import { SettingsRow } from "./settings-row";
import { authenticatedFetch } from "@/lib/native/native-auth-token";
import { syncTrainingCalendar } from "@/lib/native/calendar";
import { useI18n } from "@/lib/i18n-provider";
import { CARDIO_CALENDAR_LABELS } from "@/features/calendar/cardio-labels";
import { DEFAULT_SETTINGS, type InitialSettings } from "@/features/settings/types";

const weekdays = ["weekdayMon", "weekdayTue", "weekdayWed", "weekdayThu", "weekdayFri", "weekdaySat", "weekdaySun"] as const;
const hhmm = (minutes: number) => `${String(Math.floor(minutes / 60)).padStart(2, "0")}:${String(minutes % 60).padStart(2, "0")}`;
const toMinutes = (value: string) => { const [hours, minutes] = value.split(":").map(Number); return Number.isFinite(hours) && Number.isFinite(minutes) ? hours * 60 + minutes : 1080; };

export function CalendarSettingsSection({ kind }: { kind: "training" | "cardio" }) {
  const { t } = useI18n(); const cardio = kind === "cardio"; const [settings, setSettings] = useState<InitialSettings>(DEFAULT_SETTINGS); const [saving, setSaving] = useState(false);
  useEffect(() => { void authenticatedFetch("/api/settings", { credentials: "include" }).then((r) => r.ok ? r.json() : null).then((json) => json?.data && setSettings(json.data)).catch(() => {}); }, []);
  const enabled = cardio ? settings.cardioSyncEnabled : settings.calendarSyncEnabled; const selected = cardio ? settings.cardioWeekdays : settings.trainingWeekdays; const time = cardio ? settings.cardioTimeMinutes : settings.trainingTimeMinutes; const duration = cardio ? settings.cardioDurationMinutes : settings.trainingDurationMinutes;
  function setEnabled(value: boolean) { setSettings(cardio ? { ...settings, cardioSyncEnabled: value } : { ...settings, calendarSyncEnabled: value }); }
  function toggle(day: number) { const value = selected.includes(day) ? selected.filter((item) => item !== day) : [...selected, day].sort((a, b) => a - b); setSettings(cardio ? { ...settings, cardioWeekdays: value } : { ...settings, trainingWeekdays: value }); }
  function setTime(value: string) { setSettings(cardio ? { ...settings, cardioTimeMinutes: toMinutes(value) } : { ...settings, trainingTimeMinutes: toMinutes(value) }); }
  function setDuration(value: number) { setSettings(cardio ? { ...settings, cardioDurationMinutes: value } : { ...settings, trainingDurationMinutes: value }); }
  async function save() { setSaving(true); const body = cardio ? { cardioSyncEnabled: settings.cardioSyncEnabled, cardioWeekdays: settings.cardioWeekdays, cardioTimeMinutes: settings.cardioTimeMinutes, cardioDurationMinutes: settings.cardioDurationMinutes, cardioLabel: settings.cardioLabel } : { calendarSyncEnabled: settings.calendarSyncEnabled, trainingWeekdays: settings.trainingWeekdays, trainingTimeMinutes: settings.trainingTimeMinutes, trainingDurationMinutes: settings.trainingDurationMinutes }; const res = await authenticatedFetch("/api/settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, credentials: "include", body: JSON.stringify(body) }); setSaving(false); if (res.ok) void syncTrainingCalendar(); }
  const prefix = cardio ? "cardio" : "training";
  return <div className="space-y-5"><div className="ios-group"><label className="ios-row" htmlFor={`${prefix}-enabled`}><span className="flex-1">{t(cardio ? "settings.cardioSyncToggle" : "settings.calendarSyncToggle")}</span><input id={`${prefix}-enabled`} type="checkbox" checked={enabled} onChange={(e) => setEnabled(e.target.checked)} className="h-5 w-5 accent-primary" /></label><div className="ios-row"><span className="flex-1">{t("settings.trainingDaysLabel")}</span><div className="flex gap-1.5">{weekdays.map((key, index) => <button key={key} type="button" onClick={() => toggle(index)} className={`h-8 w-8 rounded-full text-xs font-medium ${selected.includes(index) ? "bg-primary text-primary-foreground" : "bg-[var(--sys-fill)] text-[var(--sys-label2)]"}`}>{t(`settings.${key}`)}</button>)}</div></div><label className="ios-row" htmlFor={`${prefix}-time`}><span className="flex-1">{t(cardio ? "settings.cardioTime" : "settings.trainingTime")}</span><input id={`${prefix}-time`} type="time" value={hhmm(time)} onChange={(e) => setTime(e.target.value)} className="bg-transparent text-right text-[0.9375rem] text-[var(--sys-label2)] outline-none" /></label><label className="ios-row" htmlFor={`${prefix}-duration`}><span className="flex-1">{t(cardio ? "settings.cardioDuration" : "settings.trainingDuration")}</span><input id={`${prefix}-duration`} type="number" min={1} max={1439} value={duration} onChange={(e) => setDuration(Number(e.target.value))} className="w-16 bg-transparent text-right text-[0.9375rem] text-[var(--sys-label2)] outline-none" /><span className="text-sm text-[var(--sys-label3)]">min</span></label>{cardio && <label className="ios-row" htmlFor="cardio-label"><span className="flex-1">{t("settings.cardioLabelLabel")}</span><span className="relative"><select id="cardio-label" value={settings.cardioLabel} onChange={(e) => setSettings({ ...settings, cardioLabel: e.target.value })} className="appearance-none bg-transparent pr-5 text-right text-[0.9375rem] text-[var(--sys-label2)] outline-none">{CARDIO_CALENDAR_LABELS.map((label) => <option key={label || "default"} value={label}>{label || "Cardio"}</option>)}</select><ChevronDown className="pointer-events-none absolute right-0 top-1 h-3.5 w-3.5 text-[var(--sys-label3)]" /></span></label>}<SettingsRow href={`/settings/calendar?kind=${kind}`} icon={cardio ? HeartPulse : CalendarDays} label={t("settings.editDays")} /></div><p className="ios-section-footer">{Capacitor.isNativePlatform() ? t(cardio ? "settings.cardioHint" : "settings.calendarHint") : t(cardio ? "settings.cardioWebHint" : "settings.calendarWebHint")}</p><Button className="w-full" size="lg" onClick={save} disabled={saving}>{saving ? t("common.saving") : t("common.save")}</Button></div>;
}
