import Foundation
import Capacitor
import EventKit

@objc(EventKitPlugin)
public class EventKitPlugin: CAPPlugin, CAPBridgedPlugin {
    public let identifier = "EventKitPlugin"
    public let jsName = "EventKitCalendar"
    public let pluginMethods: [CAPPluginMethod] = [CAPPluginMethod(name: "getAuthorizationStatus", returnType: CAPPluginReturnPromise), CAPPluginMethod(name: "requestAccess", returnType: CAPPluginReturnPromise), CAPPluginMethod(name: "syncEvents", returnType: CAPPluginReturnPromise), CAPPluginMethod(name: "removeAllEvents", returnType: CAPPluginReturnPromise)]
    private let store = EKEventStore()
    private func key(_ name: String) -> String { "fittrack-calendar-identifier-\(name)" }
    @objc func getAuthorizationStatus(_ call: CAPPluginCall) { let status = EKEventStore.authorizationStatus(for: .event); call.resolve(["status": status == .fullAccess ? "fullAccess" : status == .notDetermined ? "notDetermined" : status == .writeOnly ? "writeOnly" : status == .denied ? "denied" : "restricted"]) }
    @objc func requestAccess(_ call: CAPPluginCall) { store.requestFullAccessToEvents { granted, error in if let error { call.reject(error.localizedDescription) } else { call.resolve(["granted": granted]) } } }
    @objc func syncEvents(_ call: CAPPluginCall) { guard EKEventStore.authorizationStatus(for: .event) == .fullAccess, let name = call.getString("calendarName"), let items = call.getArray("events") else { call.reject("Calendar access not granted or missing events"); return }; DispatchQueue.global(qos: .userInitiated).async { do { let calendar = try self.calendar(name); let removed = try self.removeFuture(calendar); let formatter = DateFormatter(); formatter.dateFormat = "yyyy-MM-dd"; formatter.timeZone = .current; var created = 0; for case let item as [String: Any] in items { guard let date = item["date"] as? String, let title = item["title"] as? String, let minutes = item["startMinutes"] as? Int, let duration = item["durationMinutes"] as? Int, let day = formatter.date(from: date) else { continue }; let event = EKEvent(eventStore: self.store); event.calendar = calendar; event.title = title; event.notes = item["notes"] as? String; event.startDate = day.addingTimeInterval(TimeInterval(minutes * 60)); event.endDate = event.startDate.addingTimeInterval(TimeInterval(duration * 60)); try self.store.save(event, span: .thisEvent, commit: false); created += 1 }; try self.store.commit(); call.resolve(["created": created, "removed": removed]) } catch { call.reject("Calendar sync failed: \(error.localizedDescription)") } } }
    @objc func removeAllEvents(_ call: CAPPluginCall) { guard EKEventStore.authorizationStatus(for: .event) == .fullAccess, let name = call.getString("calendarName") else { call.reject("Calendar access not granted"); return }; DispatchQueue.global(qos: .userInitiated).async { do { guard let calendar = self.find(name) else { call.resolve(["removed": 0]); return }; let removed = try self.removeFuture(calendar); try self.store.commit(); call.resolve(["removed": removed]) } catch { call.reject("Calendar cleanup failed: \(error.localizedDescription)") } } }
    private func find(_ name: String) -> EKCalendar? { if let id = UserDefaults.standard.string(forKey: key(name)), let calendar = store.calendar(withIdentifier: id), calendar.title == name { return calendar }; return store.calendars(for: .event).first { $0.title == name && $0.allowsContentModifications } }
    private func calendar(_ name: String) throws -> EKCalendar { if let existing = find(name) { return existing }; let calendar = EKCalendar(for: .event, eventStore: store); calendar.title = name; guard let source = store.defaultCalendarForNewEvents?.source ?? store.sources.first(where: { $0.sourceType == .local }) else { throw NSError(domain: "EventKitPlugin", code: 1) }; calendar.source = source; try store.saveCalendar(calendar, commit: true); UserDefaults.standard.set(calendar.calendarIdentifier, forKey: key(name)); return calendar }
    private func removeFuture(_ calendar: EKCalendar) throws -> Int { let now = Date(); let events = store.events(matching: store.predicateForEvents(withStart: now, end: now.addingTimeInterval(730 * 86400), calendars: [calendar])).filter { $0.startDate >= now }; for event in events { try store.remove(event, span: .thisEvent, commit: false) }; return events.count }
}
